In [1]:
%%capture

%cd ..
%load_ext autoreload
%autoreload 2

In [15]:
from pathlib import Path
import pandas as pd
import numpy as np
import json

# Data Acquisition and Preparation

In [16]:
RAW_DATA_FOLDER = Path('data/raw/')
INTERMEDIATE_DATA_FOLDER = Path('data/interim/')
REFERENCE_FOLDER = Path('references/')

## Functions

In [17]:
def create_text_dataframe(folder):
    df_dict = {}
    for filepath in folder.glob("*.txt"):
        with open(filepath, 'r', encoding='utf-8') as f:
            df_dict[filepath.stem] = f.read() 
    return pd.DataFrame.from_dict(df_dict, orient='index', columns=['text'])

def create_metadata_datasets(folder, metadata_columns, metadata_dtypes):
    df_dict = {}
    df_dict = {k:[] for k in metadata_columns}
    df_dict["index"] = []
    
    for filepath in list(folder.glob("*.txt")):
        with open(filepath, 'r') as f:    
            df_dict["index"].append(filepath.stem.split("-")[0])
            for col, value in zip(metadata_columns, f.readlines()):
                df_dict[col].append(value[0:-1])
    
    df = pd.DataFrame(df_dict)
    df = df.replace("None", np.nan)
    df = df.astype(metadata_dtypes, errors='ignore').set_index("index", drop=True)
    df.index.name = None
    
    return df

## Preparing Dataset

In [18]:
FAKE_DATA_FOLDER = RAW_DATA_FOLDER / 'fake'
TRUE_DATA_FOLDER = RAW_DATA_FOLDER / 'true'
FAKE_META_FOLDER = RAW_DATA_FOLDER / 'fake-meta-information'
TRUE_META_FOLDER = RAW_DATA_FOLDER / 'true-meta-information'

### Text datasets

In [19]:
fake_text_df = create_text_dataframe(FAKE_DATA_FOLDER)
true_text_df = create_text_dataframe(TRUE_DATA_FOLDER)

### Metadata Datasets

In [20]:
metadata_columns = [
    "author", "link", "category", "date_of_publication",
    "tokens", "words_no_punctuation", "types", "links_inside", 
    "upper_words", "verbs", "subjuntive_imperative_verbs",
    "nouns", "adjectives", "adverbs", "modal_verbs", 
    "singular_first_second_personal_pronouns",
    "plural_first_personal_pronouns", "pronouns",
    "pausality", "characters", "average_sentence_length",
    "average_word_lenght", "percentage_spelling_errors",
    "emotiveness", "diversity"
]

metadata_translate = [
    "author", "link", "category", "date of publication", "number of tokens",
    "number of words without punctuation", "number of types",
    "number of links inside the news", "number of words in upper case",
    "number of verbs", "number of subjuntive and imperative verbs",
    "number of nouns", "number of adjectives", "number of adverbs",
    "number of modal verbs (mainly auxiliary verbs)",
    "number of singular first and second personal pronouns",
    "number of plural first personal pronouns", "number of pronouns",
    "pausality", "number of characters", "average sentence length",
    "average word length", "percentage of news with speeling errors",
    "emotiveness", "diversity"
]

metadata_dtypes = {
    "author": "string", "link": "string", "category": "string",
    "date_of_publication": "datetime64[ns]",
    "tokens": "float", "words_no_punctuation": "float",
    "types": "float","links_inside": "float", "upper_words": "float",
    "verbs": "float", "subjuntive_imperative_verbs": "float", "nouns": "float", 
    "adjectives": "float", "adverbs": "float","modal_verbs": "float", 
    "singular_first_second_personal_pronouns": "float",
    "plural_first_personal_pronouns": "float", "pronouns": "float","characters": "float",
    "pausality": "float", "average_sentence_length": "float",
    "average_word_lenght": "float", "percentage_spelling_errors": "float",
    "emotiveness": "float", "diversity": "float"
}

In [21]:
fake_metadata_df = create_metadata_datasets(FAKE_META_FOLDER, metadata_columns, metadata_dtypes)
true_metadata_df = create_metadata_datasets(TRUE_META_FOLDER, metadata_columns, metadata_dtypes)

In [22]:
true_metadata_df.links_inside.unique()

array([ 0., nan])

In [23]:
true_metadata_df[true_metadata_df.links_inside.isna()]

author  \
2175                                         Por G1 DF    
1179   Luiz Vassallo, Rafael Moraes Moura, Breno Pir...   
2335   Por Erick Gimenes e José Vianna, G1 PR, Curit...   
243   Bernardo Caram, Alessandra Modzeleski E Fernan...   
1596                                            Por G1    
...                                                 ...   
1127                                           Por BBC    
2931      Por Matheus Rodrigues e Cássio Bruno, G1 Rio    
3392                                           Por BBC    
2922                        Por Fernanda Borges, G1 GO    
7                                                 G1 MA   

                                                   link             category  \
2175  https://g1.globo.com/df/distrito-federal/notic...  sociedade_cotidiano   
1179  http://politica.estadao.com.br/blogs/fausto-ma...      tv_celebridades   
2335  https://g1.globo.com/pr/parana/noticia/moro-de...      tv_celebridades   
243   https://g1.globo.com/politica/noticia/rodrigo-...             politica   
1596  https://g1.globo.com/pop-arte/cinema/noticia/i...  sociedade_cotidiano   
...                                                 ...                  ...   
1127  https://g1.globo.com/politica/noticia/essa-ide...             politica   
2931  https://g1.globo.com/rj/rio-de-janeiro/noticia...             politica   
3392  https://g1.globo.com/economia/tecnologia/notic...             politica   
2922  https://g1.globo.com/goias/noticia/ex-deputado...             politica   
7     https://g1.globo.com/ma/maranhao/noticia/minis...  sociedade_cotidiano   

           date_of_publication  tokens  words_no_punctuation  types  \
2175         22/03/2018 07h10    741.0                 640.0  361.0   
1179   23 de setembro de 2017   1289.0                1173.0  529.0   
2335         28/04/2017 18h52    429.0                 387.0  206.0   
243                 14/12/2017   599.0                 505.0  241.0   
1596         07/09/2017 08h32    989.0                 829.0  469.0   
...                        ...     ...                   ...    ...   
1127         19/05/2017 09h24   1014.0                 855.0  416.0   
2931         19/11/2017 12h53    974.0                 812.0  430.0   
3392         21/03/2018 13h40   1149.0                1035.0  458.0   
2922         14/04/2017 11h39   1797.0                1563.0  624.0   
7                   27/11/2017   502.0                 459.0  239.0   

      links_inside  upper_words  verbs  ...  \
2175           NaN          5.0   76.0  ...   
1179           NaN         14.0  146.0  ...   
2335           NaN          1.0   64.0  ...   
243            NaN          4.0   88.0  ...   
1596           NaN          4.0  125.0  ...   
...            ...          ...    ...  ...   
1127           NaN          2.0  150.0  ...   
2931           NaN          8.0  111.0  ...   
3392           NaN          8.0  175.0  ...   
2922           NaN         19.0  223.0  ...   
7              NaN         12.0   49.0  ...   

      singular_first_second_personal_pronouns  plural_first_personal_pronouns  \
2175                                      0.0                             0.0   
1179                                      0.0                             0.0   
2335                                      0.0                             0.0   
243                                       3.0                             4.0   
1596                                      0.0                             0.0   
...                                       ...                             ...   
1127                                      1.0                             1.0   
2931                                      1.0                             0.0   
3392                                      1.0                             2.0   
2922                                      4.0                             0.0   
7                                         0.0                         

In [24]:
fake_metadata_df.links_inside.unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  9., 11.,  6.,  8.])

## Merging Created Datasets

### Fake Dataset

In [25]:
fake_df = pd.concat([fake_text_df, fake_metadata_df], axis=1, sort=False)
fake_df.index = fake_df.index.astype(int)
fake_df = fake_df.sort_index()
fake_df = fake_df.reset_index(drop=True)

In [26]:
fake_metadata_df.links_inside.unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  9., 11.,  6.,  8.])

### True Dataset

In [27]:
true_df = pd.concat([true_text_df, true_metadata_df], axis=1, sort=False)
true_df.index = true_df.index.astype(int)
true_df = true_df.sort_index()
true_df = true_df.reset_index(drop=True)

In [28]:
true_df.links_inside.unique()

array([nan,  0.])

## Merge All Datasets

In [29]:
result = pd.concat([true_df, fake_df], keys=['True', 'Fake'])
result = result.reset_index(level=0).rename(columns={"level_0": "class"})

result.to_csv(INTERMEDIATE_DATA_FOLDER/"fake_true_news.csv", index=False)

## Columns Information

In [30]:
columns_info ={}
columns_info['text'] = 'Text extracted from the news'
for var, desc in zip(metadata_columns, metadata_translate):
    columns_info[var] = desc

In [31]:
with open(REFERENCE_FOLDER / "news_data_dictionary.json","w") as f:
    f.write(json.dumps(columns_info))
    f.close()